#!/usr/bin/env python3
"""Benchmark Hearth engines + HTTP endpoints; write docs/benchmarks.md.

Isolated state (HEARTH_STATE_DIR=/tmp/hearth-bench) so runs never touch the
dev tree. Read-only calls only — no proposals decided, no hardware touched.
"""
import json
import os
import statistics
import sys
import tempfile
import time

os.environ["HEARTH_STATE_DIR"] = tempfile.mkdtemp(prefix="hearth-bench-")

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "src"))
sys.path.insert(0, os.path.join(ROOT, "mcp-server"))

from starlette.testclient import TestClient  # noqa: E402
import server  # noqa: E402
from hearth import parliament, causal_twin, forensics, acoustic, mediation, swarm  # noqa: E402

N = 20


def timeit(fn, n=N):
    ds = []
    for _ in range(n):
        t = time.perf_counter()
        fn()
        ds.append((time.perf_counter() - t) * 1000)
    ds.sort()
    return {
        "n": n,
        "p50_ms": round(ds[n // 2], 2),
        "p95_ms": round(ds[min(n - 1, int(n * 0.95))], 2),
        "max_ms": round(ds[-1], 2),
    }


def main():
    client = TestClient(server.mcp.streamable_http_app())
    engines = {
        "parliament.deliberate": lambda: parliament.parliament.deliberate(
            "bench", {"peak_tariff": 0.48, "target_temp": 71, "battery_soc": 84}),
        "causal_twin.run(7d/100it)": lambda: causal_twin.causal_twin.run_simulation(
            days_ahead=7, iterations=100),
        "forensics.reconstruct": lambda: forensics.forensics_engine.reconstruct_incident(
            "perimeter_anomaly"),
        "acoustic.scan": lambda: acoustic.acoustic_doctor.scan_appliance_acoustics(
            stage_remedy=False),
        "mediation.treaty": lambda: mediation.family_mediator.draft_household_treaty(),
        "swarm.dispatch": lambda: swarm.swarm_grid.coordinate_microgrid(3.8),
    }
    endpoints = {
        "GET /health": lambda: client.get("/health"),
        "GET /api/causal/vulnerabilities": lambda: client.get("/api/causal/vulnerabilities"),
        "GET /api/swarm/grid": lambda: client.get("/api/swarm/grid"),
        "GET /api/acoustic/scan": lambda: client.get("/api/acoustic/scan"),
        "POST /api/parliament/deliberate": lambda: client.post(
            "/api/parliament/deliberate", json={"topic": "bench"}),
    }
    eng_rows = {k: timeit(v) for k, v in engines.items()}
    http_rows = {k: timeit(v) for k, v in endpoints.items()}

    # Twin scaling curve (fewer iters for time)
    scaling = []
    for it in (50, 100, 150, 300):
        t = time.perf_counter()
        sim = causal_twin.causal_twin.run_simulation(days_ahead=7, iterations=it)
        dt = (time.perf_counter() - t) * 1000
        scaling.append({"iterations": it, "wall_ms": round(dt, 1),
                        "vulns": len(sim.vulnerabilities),
                        "savings": sim.expected_savings_usd})

    lines = ["# Benchmarks: Latency Evidence (reproducible)",
             "",
             "> Generated by `python3 scripts/bench_tools.py` (isolated state, "
             f"{N} samples each, Python {sys.version.split()[0]}).",
             f"> Rerun anytime; numbers below were measured on {time.strftime('%Y-%m-%d')}.",
             "",
             "## Engine latency (in-process, ms)",
             "",
             "| engine | p50 | p95 | max |",
             "|---|---|---|---|"]
    for k, v in eng_rows.items():
        lines.append(f"| `{k}` | {v['p50_ms']} | {v['p95_ms']} | {v['max_ms']} |")
    lines += ["", "## HTTP endpoint latency (TestClient, ms)", "",
              "| endpoint | p50 | p95 | max |", "|---|---|---|---|"]
    for k, v in http_rows.items():
        lines.append(f"| `{k}` | {v['p50_ms']} | {v['p95_ms']} | {v['max_ms']} |")
    lines += ["", "## Causal Twin scaling (7-day horizon)", "",
              "| iterations | wall ms | vulnerabilities | savings $ |",
              "|---|---|---|---|"]
    for s in scaling:
        lines.append(f"| {s['iterations']} | {s['wall_ms']} | {s['vulns']} | {s['savings']} |")
    worst = max([v["p95_ms"] for v in eng_rows.values()]
                + [v["p95_ms"] for v in http_rows.values()])
    lines += ["",
              f"**Verdict:** worst measured p95 = **{worst} ms** "
              f"({'within' if worst < 500 else 'ABOVE'} the 500ms "
              "`latencyTargetMs` in `addon.json`).",
              ""]
    out = os.path.join(ROOT, "docs", "benchmarks.md")
    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    raw = {"engines": eng_rows, "http": http_rows, "scaling": scaling}
    with open(os.path.join(ROOT, "docs", "benchmarks.json"), "w") as f:
        json.dump(raw, f, indent=2)
    print(f"worst p95: {worst} ms -> {out}")


if __name__ == "__main__":
    main()
